name: CI Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      
      - name: Install frontend dependencies
        run: |
          if [ -d "frontend" ]; then
            cd frontend
            npm install
          fi

      
      - name: Install backend dependencies
        run: |
          if [ -d "backend" ]; then
            cd backend
            npm install
          fi

      
      - name: Build Docker image
        run: |
          if [ -f "backend/Dockerfile" ]; then
            cd backend
            docker build -t shop-smart .
          elif [ -f "Dockerfile" ]; then
            docker build -t shop-smart .
          fi